--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Leqends/PvP-Aspects-Manager
build-by-default: true
branches:
- master
projects:
  PvP-Aspects-Manager:
    path: ""
    libs:
    - src: "CortexPE/Commando/Commando"
      branch: "PM4"
      version: ^3.0.0
...
