name: PvP Aspects Manager
main: HeliosTeam\PAM\Manager
authors:
  - zMxZero/Leqends
  - Eerie6560
  - KingRainbow44

version: "1.0.0-Release"
api: 4.0.0
description: "PvP Aspects Manager: A PvP Manager containing Knockback and Delay Management"

permissions:
  attackdelay.cmd:
    description: "Permission for Attack Delay Command"
    default: op
  knockback.cmd:
    description: "Permission for Knockback Command"
    default: op
