name: PvP Aspects Manager
main: HeliosTeam\PAM\Manager
authors:
  - zMxZero/Leqends
  - Eerie6560
version: "2.0.0 Latest"
api: 4.0.0
description: "PvP Aspects Manager: A PvP Manager containing Knockback (X & Y) and Delay Management"
commands:
  attackdelay:
    permission: "attackdelay.cmd"
    description: "The command to set the attack delay"
    usage: "attackdelay {world} {value}"
    aliases:
      - "adm"
      - "ad"
  knockback:
    permission: "knockback.cmd"
    description: "The command to set the knockback"
    usage: "knockback {world} {value}"
    aliases:
      - "kb"
      - "kbm"

permissions:
  attackdelay.cmd:
    description: "Permission for Attack Delay Command"
    default: op
  knockback.cmd:
    description: "Permission for Knockback Command"
    default: op
